stages:

  extract_calibration_images:
    cmd: python scripts/camera_calibration.py extract-calibration-images --video_dir data/raw/calibration/video/calibration.mov --path_to_images_folder data/raw/calibration/images --amount_of_frames 45
    deps:
      - scripts/camera_calibration.py
      - data/raw/calibration/video
    outs:
      - data/raw/calibration/images

  camera_calibration:
    cmd: python scripts/camera_calibration.py calibrate --image_dir data/raw/calibration/images --image_format jpg --output_path data/processed/colmap_db/colmap_text/ --square_size 2
    deps:
      - scripts/camera_calibration.py
      - data/raw/calibration/images
    outs:
      - data/processed/colmap_db/colmap_text/cameras.txt

  extract_images_from_video:
    cmd: python scripts/image_preprocessing.py extract-images-from-video --path_to_video data/raw/video/video.mov --path_to_images_folder data/raw/images --amount_of_frames 150 --metadata data/raw/meta/meta.json --colmap_text_folder data/processed/colmap_db/colmap_text
    deps:
      - data/raw/meta/theta.json
      - data/raw/meta/meta.json
      - scripts/image_preprocessing.py
      - data/raw/video
      - data/processed/colmap_db/colmap_text/cameras.txt
    outs:
      - data/raw/images
      - data/processed/colmap_db/colmap_text/images.txt

  crop_and_resize_images:
    cmd: python scripts/image_preprocessing.py crop-resize-images --path_to_images_folder data/raw/images --path_to_cropped_images_folder data/interim/
    deps:
      - scripts/image_preprocessing.py
      - data/raw/images
    outs:
      - data/interim

  remove_background:
    cmd: python scripts/image_preprocessing.py remove-background --path_to_cropped_images_folder data/interim/ --images_no_background data/processed/images --model_type new
    deps:
      - scripts/image_preprocessing.py
      - data/interim/
    outs:
      - data/processed/images/

  colmap2nerf:
    cmd: python scripts/colmap2nerf.py --image_folder data/processed/images --colmap_text_folder data/processed/colmap_db/colmap_text --output data/processed/configs/nerf_transforms.json
    deps:
      - data/processed/images/
      - scripts/colmap2nerf.py
      - data/processed/colmap_db/
    outs:
      - data/processed/configs/nerf_transforms.json

  reconstruction-base-run:
   cmd: python scripts/reconstruction.py base-run --ref_mesh data/processed/configs --out_dir data/results
   params:
     - iter
     - batch
     - spp
     - layers
     - train_res
     - texture_res
     - save_interval
     - learning_rate
   metrics:
     - data/results/metrics.json
   deps:
     - data/processed/irrmaps
     - data/processed/tets
     - scripts/reconstruction.py
     - data/processed/configs/nerf_transforms.json
   outs:
     - data/results/eval_mesh
     - data/results/train_images
     
#   reconstruction-refinement:
#    cmd: python scripts/reconstruction.py refinement-run --path_to_flags data/results/artefact_storage/FLAGS.pickle
#    deps:
#      - data/processed/irrmaps
#      - data/processed/tets
#      - scripts/reconstruction.py
#      - data/processed/configs/nerf_transforms.json
#      - data/results/artefact_storage